export { default as AdminPageLayout } from './AdminPageLayout';
export { default as AdminPageHeader } from './AdminPageHeader';
export { default as AdminPageContent } from './AdminPageContent';
export { default as AdminPageActions } from './AdminPageActions';
export { default as AdminSidebar } from './AdminSidebar';
export { default as AdminTabsContainer } from './AdminTabsContainer';
export { AdminTabs, AdminTabContent } from './AdminTabs';
export { TabSystemMigration } from '../migration/TabSystemMigration';
export type { AdminPageConfig, AdminPageAction } from './AdminPageLayout';
export type { AdminTabConfig } from './AdminTabs';
export { AdminSimplifiedLayout } from './AdminSimplifiedLayout';
