
import React, { useState } from 'react';
import { 
  Card, 
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useEventMarketing } from '@/hooks/events/useEventMarketing';
import { EventMarketingCampaign } from '@/types/EventTypes';
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, BarChart3, Mail, Share2, Tag, Target } from 'lucide-react';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';

interface MarketingTabContentProps {
  eventId: string;
}

const MarketingTabContent: React.FC<MarketingTabContentProps> = ({ eventId }) => {
  const [activeCampaign, setActiveCampaign] = useState<EventMarketingCampaign | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [formData, setFormData] = useState<{
    name: string;
    description: string;
    campaign_type: string;
    status: 'draft' | 'active' | 'completed' | 'cancelled';
  }>({
    name: '',
    description: '',
    campaign_type: 'social',
    status: 'draft'
  });
  
  const { 
    campaigns, 
    isLoading, 
    error, 
    createCampaign, 
    updateCampaign, 
    deleteCampaign,
    getCampaignLink 
  } = useEventMarketing(eventId);

  const handleCreateCampaign = async () => {
    try {
      const newCampaign = await createCampaign({
        id: '', // This will be generated by the database
        event_id: '', // This will be set in the service
        name: formData.name,
        description: formData.description,
        campaign_type: formData.campaign_type,
        status: formData.status,
        metrics: {
          impressions: 0,
          clicks: 0,
          conversions: 0,
          revenue: 0,
          open_rate: 0
        }
      });
      setIsCreating(false);
      resetForm();
    } catch (error) {
      console.error('Error creating campaign:', error);
    }
  };

  const handleUpdateCampaign = async () => {
    if (!activeCampaign) return;
    
    try {
      await updateCampaign(activeCampaign.id, {
        name: formData.name,
        description: formData.description,
        campaign_type: formData.campaign_type,
        status: formData.status
      });
      setIsEditing(false);
      setActiveCampaign(null);
    } catch (error) {
      console.error('Error updating campaign:', error);
    }
  };

  const handleDeleteCampaign = async (id: string) => {
    try {
      await deleteCampaign(id);
      if (activeCampaign?.id === id) {
        setActiveCampaign(null);
        setIsEditing(false);
      }
    } catch (error) {
      console.error('Error deleting campaign:', error);
    }
  };

  const handleEditCampaign = (campaign: EventMarketingCampaign) => {
    setActiveCampaign(campaign);
    setFormData({
      name: campaign.name,
      description: campaign.description || '',
      campaign_type: campaign.campaign_type,
      status: campaign.status as 'draft' | 'active' | 'completed' | 'cancelled'
    });
    setIsEditing(true);
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      campaign_type: 'social',
      status: 'draft'
    });
  };

  const handleCancelEdit = () => {
    setIsEditing(false);
    setIsCreating(false);
    setActiveCampaign(null);
    resetForm();
  };

  const getChartData = (campaign: EventMarketingCampaign) => {
    const metrics = campaign.metrics || {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      revenue: 0
    };
    
    return [
      { name: 'Impressions', value: metrics.impressions },
      { name: 'Clicks', value: metrics.clicks },
      { name: 'Conversions', value: metrics.conversions }
    ];
  };

  const getCampaignTypeIcon = (type: string) => {
    switch (type) {
      case 'social': return <Share2 className="h-4 w-4" />;
      case 'email': return <Mail className="h-4 w-4" />;
      case 'promo': return <Tag className="h-4 w-4" />;
      default: return <Target className="h-4 w-4" />;
    }
  };

  const getCampaignTypeLabel = (type: string) => {
    switch (type) {
      case 'social': return 'Social Media';
      case 'email': return 'Email Marketing';
      case 'promo': return 'Promotional Code';
      default: return 'Other';
    }
  };

  const getConversionRate = (campaign: EventMarketingCampaign) => {
    const metrics = campaign.metrics || {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      revenue: 0
    };
    if (!metrics.impressions) return 0;
    return ((metrics.conversions / metrics.impressions) * 100).toFixed(2);
  };

  const getClickThroughRate = (campaign: EventMarketingCampaign) => {
    const metrics = campaign.metrics || {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      revenue: 0
    };
    if (!metrics.impressions) return 0;
    return ((metrics.clicks / metrics.impressions) * 100).toFixed(2);
  };

  const getOpenRate = (campaign: EventMarketingCampaign) => {
    const metrics = campaign.metrics || {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      revenue: 0,
      open_rate: 0
    };
    return (metrics.open_rate || 0).toFixed(2);
  };

  return (
    <div>
      <Tabs defaultValue="campaigns" className="w-full">
        <TabsList className="mb-4">
          <TabsTrigger value="campaigns">Campaigns</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
          <TabsTrigger value="audience">Audience</TabsTrigger>
        </TabsList>

        <TabsContent value="campaigns">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h3 className="text-lg font-medium">Marketing Campaigns</h3>
              <p className="text-sm text-muted-foreground">Create and manage event marketing campaigns</p>
            </div>
            {!isCreating && !isEditing && (
              <Button onClick={() => setIsCreating(true)}>Create Campaign</Button>
            )}
          </div>

          {error && (
            <Alert variant="destructive" className="mb-4">
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {(isCreating || isEditing) && (
            <Card className="mb-6">
              <CardHeader>
                <CardTitle>{isEditing ? 'Edit Campaign' : 'Create Campaign'}</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <Label htmlFor="name">Campaign Name</Label>
                    <Input
                      id="name" 
                      value={formData.name} 
                      onChange={(e) => setFormData({...formData, name: e.target.value})}
                      placeholder="Campaign Name"
                    />
                  </div>
                  
                  <div>
                    <Label htmlFor="description">Description</Label>
                    <Textarea
                      id="description" 
                      value={formData.description} 
                      onChange={(e) => setFormData({...formData, description: e.target.value})}
                      placeholder="Campaign Description"
                    />
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="type">Campaign Type</Label>
                      <Select 
                        value={formData.campaign_type}
                        onValueChange={(value) => setFormData({...formData, campaign_type: value})}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select campaign type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="social">Social Media</SelectItem>
                          <SelectItem value="email">Email Marketing</SelectItem>
                          <SelectItem value="promo">Promotional Code</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    
                    <div>
                      <Label htmlFor="status">Status</Label>
                      <Select 
                        value={formData.status}
                        onValueChange={(value: 'draft' | 'active' | 'completed' | 'cancelled') => 
                          setFormData({...formData, status: value})
                        }
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select status" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="draft">Draft</SelectItem>
                          <SelectItem value="active">Active</SelectItem>
                          <SelectItem value="completed">Completed</SelectItem>
                          <SelectItem value="cancelled">Cancelled</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  
                  <div className="flex justify-end space-x-2 pt-4">
                    <Button variant="outline" onClick={handleCancelEdit}>Cancel</Button>
                    <Button onClick={isEditing ? handleUpdateCampaign : handleCreateCampaign}>
                      {isEditing ? 'Update' : 'Create'}
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {isLoading ? (
            <div className="flex justify-center p-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-800"></div>
            </div>
          ) : campaigns.length === 0 ? (
            <div className="text-center py-8">
              <p className="text-muted-foreground">No marketing campaigns created yet.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {campaigns.map((campaign) => (
                <Card key={campaign.id} className="overflow-hidden">
                  <CardHeader className="pb-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-2">
                        {getCampaignTypeIcon(campaign.campaign_type)}
                        <span className="text-xs bg-muted px-2 py-1 rounded">
                          {getCampaignTypeLabel(campaign.campaign_type)}
                        </span>
                      </div>
                      <div>
                        <span className={`text-xs px-2 py-1 rounded ${
                          campaign.status === 'active' ? 'bg-green-100 text-green-800' :
                          campaign.status === 'completed' ? 'bg-blue-100 text-blue-800' : 
                          campaign.status === 'cancelled' ? 'bg-red-100 text-red-800' :
                          'bg-amber-100 text-amber-800'
                        }`}>
                          {campaign.status.charAt(0).toUpperCase() + campaign.status.slice(1)}
                        </span>
                      </div>
                    </div>
                    <CardTitle className="text-lg">{campaign.name}</CardTitle>
                    <CardDescription className="line-clamp-2">
                      {campaign.description || 'No description provided'}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="flex justify-between items-center text-sm mb-2">
                      <div>Impressions</div>
                      <div className="font-medium">{campaign.metrics?.impressions || 0}</div>
                    </div>
                    <div className="flex justify-between items-center text-sm mb-2">
                      <div>Clicks</div>
                      <div className="font-medium">{campaign.metrics?.clicks || 0}</div>
                    </div>
                    <div className="flex justify-between items-center text-sm mb-2">
                      <div>Conversion Rate</div>
                      <div className="font-medium">{getConversionRate(campaign)}%</div>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <div>Revenue</div>
                      <div className="font-medium">${campaign.metrics?.revenue?.toFixed(2) || '0.00'}</div>
                    </div>
                    
                    <div className="mt-4 pt-4 border-t flex justify-between">
                      <div className="space-x-2">
                        <Button 
                          variant="outline" 
                          size="sm" 
                          onClick={() => handleEditCampaign(campaign)}
                        >
                          Edit
                        </Button>
                        <Button 
                          variant="outline" 
                          size="sm" 
                          className="text-red-600 hover:text-red-700"
                          onClick={() => handleDeleteCampaign(campaign.id)}
                        >
                          Delete
                        </Button>
                      </div>
                      <Button 
                        size="sm" 
                        className="flex items-center gap-1"
                        onClick={() => {
                          navigator.clipboard.writeText(getCampaignLink(campaign.id));
                          alert('Campaign link copied to clipboard!');
                        }}
                      >
                        <ArrowUpRight className="h-3 w-3" />
                        Share
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
        
        <TabsContent value="analytics">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h3 className="text-lg font-medium">Campaign Analytics</h3>
              <p className="text-sm text-muted-foreground">Track the performance of your marketing campaigns</p>
            </div>
          </div>
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {campaigns.length > 0 ? campaigns.map((campaign) => (
              <Card key={campaign.id}>
                <CardHeader>
                  <div className="flex justify-between items-center">
                    <CardTitle>{campaign.name}</CardTitle>
                    <div className="flex items-center space-x-2">
                      {getCampaignTypeIcon(campaign.campaign_type)}
                      <span className={`text-xs px-2 py-1 rounded ${
                        campaign.status === 'active' ? 'bg-green-100 text-green-800' :
                        campaign.status === 'completed' ? 'bg-blue-100 text-blue-800' : 
                        campaign.status === 'cancelled' ? 'bg-red-100 text-red-800' :
                        'bg-amber-100 text-amber-800'
                      }`}>
                        {campaign.status.charAt(0).toUpperCase() + campaign.status.slice(1)}
                      </span>
                    </div>
                  </div>
                  <CardDescription>{campaign.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-[200px] mb-4">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={getChartData(campaign)}>
                        <CartesianGrid strokeDasharray="3 3" />
                        <XAxis dataKey="name" />
                        <YAxis />
                        <Tooltip />
                        <Legend />
                        <Bar dataKey="value" fill="#8884d8" />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                  
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="bg-muted/30 rounded-lg p-3">
                      <div className="text-xs text-muted-foreground mb-1">CTR</div>
                      <div className="font-semibold">{getClickThroughRate(campaign)}%</div>
                    </div>
                    <div className="bg-muted/30 rounded-lg p-3">
                      <div className="text-xs text-muted-foreground mb-1">Conv. Rate</div>
                      <div className="font-semibold">{getConversionRate(campaign)}%</div>
                    </div>
                    <div className="bg-muted/30 rounded-lg p-3">
                      <div className="text-xs text-muted-foreground mb-1">Revenue</div>
                      <div className="font-semibold">${campaign.metrics?.revenue?.toFixed(2) || '0.00'}</div>
                    </div>
                    <div className="bg-muted/30 rounded-lg p-3">
                      <div className="text-xs text-muted-foreground mb-1">ROI</div>
                      <div className="font-semibold">
                        {campaign.budget && campaign.budget > 0 && campaign.metrics?.revenue
                          ? `${(((campaign.metrics.revenue - campaign.budget) / campaign.budget) * 100).toFixed(2)}%`
                          : 'N/A'}
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )) : (
              <Card className="col-span-2">
                <CardContent className="flex flex-col items-center justify-center p-8">
                  <BarChart3 className="h-12 w-12 text-muted-foreground mb-4" />
                  <p className="mb-2">No campaign data available</p>
                  <p className="text-sm text-muted-foreground">Create your first campaign to start tracking analytics</p>
                </CardContent>
              </Card>
            )}
          </div>
        </TabsContent>
        
        <TabsContent value="audience">
          <div className="flex justify-between items-center mb-6">
            <div>
              <h3 className="text-lg font-medium">Audience Insights</h3>
              <p className="text-sm text-muted-foreground">Understand your event audience better</p>
            </div>
          </div>
          
          <Card>
            <CardContent className="flex flex-col items-center justify-center p-8">
              <Target className="h-12 w-12 text-muted-foreground mb-4" />
              <p className="mb-2">Audience insights feature coming soon</p>
              <p className="text-sm text-muted-foreground text-center max-w-md">
                You'll soon be able to view detailed audience demographics, interests, and engagement patterns
                to better target your marketing campaigns.
              </p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default MarketingTabContent;
