
// This file serves as a bridge to the new unified detection system
// All detection logic has been moved to the FeatureDetectionEngine

import { FeatureItem } from '../types';

// Re-export everything from the unified detection index
export {
  featureDetectionEngine,
  unifiedDetection,
  isFeatureFlagRelated,
  isIngredientPairingFeature,
  isMocktailSuggestionFeature,
  isMocktailTrendsFeature,
  isRecipeFeature,
  isPromotionFeature,
  isPromotionAnalyticsFeature,
  isPromotionSecurityFeature,
  isPromotionNotificationFeature,
  isPromotionCreationFeature,
  isPromotionManagementFeature,
  isPromotionRedemptionFeature,
  isPromotionReportingFeature,
  isPromotionValidationFeature,
  isPromotionSchedulingFeature,
  isPromotionIntegrationFeature,
  isPromotionAIFeature,
  isUserManagementFeature,
  isAuthFeature,
  isProfileFeature,
  isContentFeature,
  isContentModerationFeature,
  isPhotoFeature,
  isPhotoModerationFeature,
  isSystemConfigurationFeature,
  isAnalyticsFeature,
  isDashboardFeature,
  isSystemBreakdownFeature,
  isMapFeature,
  isAIFeature,
  isExplorationFeature,
  isNotificationFeature,
  isSocialFeature,
  isRewardProgramFeature,
  isThemeFeature,
  isSwigCircuitFeature,
  isBarCrawlFeature,
  isSignatureFeature,
  isEstablishmentManagementFeature,
  isVisitTrackingFeature,
  isPromoterCommunicationFeature,
  isBrandConnectionFeature,
  isPromoterAnalyticsFeature,
  isEventManagementFeature,
  isPromoterDashboardFeature,
  isCustomPromotionFeature,
  isPromoterNotificationFeature,
  isAudienceInfluencerFeature,
  isCrossSegmentEngagementFeature,
  isAudienceVisualizationFeature,
  isAudienceRelationshipFeature,
  isTicketManagementFeature
} from './detection';
