
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvifibvzwunnpcsihpxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2aWZpYnZ6d3VubnBjc2locHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzM4MDcsImV4cCI6MjA1ODg0OTgwN30.8nsPh_YwHjoFDJ2_IMQY9tkM9NHVLmu6oFf5Tnwa2FA";

// Create a single Supabase client instance to be used throughout the app
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Always persist sessions
    autoRefreshToken: true,
    storageKey: 'spiritless-auth-storage',
    detectSessionInUrl: true, // Detect session in URL for redirects
    flowType: 'pkce' // Use PKCE flow for more reliable auth
  }
});

// Debug helper function for sessions
export const getSessionDebug = async () => {
  const { data: { session }, error } = await supabase.auth.getSession();
  console.log("Session debug:", { 
    hasSession: !!session, 
    error: error?.message,
    user: session?.user ? { 
      id: session.user.id, 
      email: session.user.email,
      emailConfirmed: !!session.user.email_confirmed_at
    } : null,
    expiresAt: session?.expires_at ? new Date(session.expires_at * 1000).toISOString() : null,
    localStorage: {
      auth: !!localStorage.getItem('spiritless-auth-storage'),
      userAuthenticated: localStorage.getItem('user_authenticated'),
      userType: localStorage.getItem('user_type')
    }
  });
  return { session, error };
};

// Auth state change tracker with consistent return signature
export const trackAuthStateChange = () => {
  const { data } = supabase.auth.onAuthStateChange((event, session) => {
    console.log(`Auth state changed: ${event}`, { 
      hasSession: !!session, 
      userId: session?.user?.id,
      userEmail: session?.user?.email
    });
  });
  
  return { 
    data: { 
      subscription: {
        unsubscribe: () => data.subscription.unsubscribe()
      }
    } 
  };
};
