
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isLovablePreview, previewLog } from '@/utils/environment';

const SUPABASE_URL = "https://dvifibvzwunnpcsihpxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2aWZpYnZ6d3VubnBjc2locHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzM4MDcsImV4cCI6MjA1ODg0OTgwN30.8nsPh_YwHjoFDJ2_IMQY9tkM9NHVLmu6oFf5Tnwa2FA";

// Configure Supabase client differently based on environment
const getSupabaseConfig = () => {
  // Special configuration for Lovable preview
  if (isLovablePreview()) {
    previewLog('Creating Supabase client with preview configuration');
    return {
      auth: {
        persistSession: false, // Don't persist session in preview mode
        autoRefreshToken: true,
        storageKey: 'spiritless-auth-preview',
        detectSessionInUrl: false, // Disable URL detection in preview
      },
      global: {
        headers: {
          'X-Lovable-Preview': 'true',
        },
      },
    };
  }
  
  // Normal configuration for production/development
  return {
    auth: {
      persistSession: true, 
      autoRefreshToken: true,
      storageKey: 'spiritless-auth-storage'
    }
  };
};

// Create and export the Supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  getSupabaseConfig()
);

// Log initialization in preview mode
if (isLovablePreview()) {
  previewLog('Supabase client initialized with preview settings');
}
