
import { FeatureItem } from '../types';
import { advancedEstablishmentTools } from './establishmentFeatures/advancedEstablishmentTools';

export const establishmentFeatures: FeatureItem[] = [
  advancedEstablishmentTools,
  {
    id: 'est-001',
    name: 'Establishment Profile Management',
    description: 'Comprehensive profile management for establishments including hours, photos, and contact info',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 95,
    category: 'business_operations'
  },
  {
    id: 'est-002',
    name: 'Menu Management System',
    description: 'Digital menu creation and management for mocktails and beverages',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 90,
    category: 'business_operations'
  },
  {
    id: 'est-003',
    name: 'Analytics Dashboard',
    description: 'Detailed analytics on customer visits, popular drinks, and revenue metrics',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'none',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 85,
    category: 'system_intelligence'
  },
  {
    id: 'est-004',
    name: 'Loyalty Program Management',
    description: 'Create and manage customer loyalty programs and rewards',
    status: 'in_progress',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'in_progress',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 65,
    category: 'business_operations'
  },
  {
    id: 'est-005',
    name: 'Customer Communication Tools',
    description: 'Direct messaging and notification system for customer engagement',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'partial',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 80,
    category: 'user_experience'
  },
  {
    id: 'est-006',
    name: 'Revenue Tracking',
    description: 'Track revenue from bar crawls, events, and individual visits',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'none',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 88,
    category: 'system_intelligence'
  },
  {
    id: 'est-007',
    name: 'Promotional Campaign Management',
    description: 'Create and manage promotional campaigns and special offers',
    status: 'in_progress',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'in_progress',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 70,
    category: 'business_operations'
  },
  {
    id: 'est-008',
    name: 'Mocktail Recommendation Engine',
    description: 'AI-powered mocktail suggestions based on customer preferences',
    status: 'not_started',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'not_started',
    userImpact: 'medium',
    complexity: 'high',
    implementationProgress: 25,
    category: 'system_intelligence'
  },
  {
    id: 'est-009',
    name: 'Operating Hours Management',
    description: 'Dynamic operating hours with special event scheduling',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'low',
    implementationProgress: 100,
    category: 'business_operations'
  },
  {
    id: 'est-010',
    name: 'Visitor Statistics',
    description: 'Real-time and historical visitor statistics and patterns',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'none',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 92,
    category: 'system_intelligence'
  },
  {
    id: 'est-011',
    name: 'Bar Crawl Participation',
    description: 'Tools to participate in and manage bar crawl events',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'read',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 95,
    category: 'business_operations'
  },
  {
    id: 'est-012',
    name: 'Push Notification System',
    description: 'Send targeted notifications to customers about events and promotions',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'full',
    individualAccess: 'partial',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 85,
    category: 'user_experience'
  }
];
