
import { FeatureItem } from '../types';
import { enhancedUserExperience } from './individualFeatures/enhancedUserExperience';

export const individualFeatures: FeatureItem[] = [
  enhancedUserExperience,
  {
    id: 'ind-001',
    name: 'User Profile System',
    description: 'Personal profile management for individual users',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 100
  },
  {
    id: 'ind-002',
    name: 'Mocktail Discovery',
    description: 'Browse and discover mocktails from various establishments',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 90
  },
  {
    id: 'ind-003',
    name: 'Bar Crawl Management',
    description: 'Create, join, and manage bar crawl experiences',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 95
  },
  {
    id: 'ind-004',
    name: 'Ticket Purchase System',
    description: 'Purchase tickets for events and bar crawls with payment integration',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 100
  },
  {
    id: 'ind-005',
    name: 'Favorites & Wishlist',
    description: 'Save favorite establishments, drinks, and events',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'low',
    implementationProgress: 100
  },
  {
    id: 'ind-006',
    name: 'Recipe Creation & Sharing',
    description: 'Create and share custom mocktail recipes',
    status: 'in_progress',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 60
  },
  {
    id: 'ind-007',
    name: 'Rewards & Points System',
    description: 'Earn and redeem points for visits and activities',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 88
  },
  {
    id: 'ind-008',
    name: 'Check-in System',
    description: 'Check into establishments and events to earn rewards',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 95
  },
  {
    id: 'ind-009',
    name: 'Social Features',
    description: 'Follow friends, share experiences, and see social activity',
    status: 'in_progress',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'medium',
    complexity: 'high',
    implementationProgress: 45
  },
  {
    id: 'ind-010',
    name: 'Mobile Profile Management',
    description: 'Optimized mobile experience for profile management',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'none',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 92
  },
  {
    id: 'ind-011',
    name: 'Notification Preferences',
    description: 'Customizable notification settings for events and updates',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'none',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'low',
    implementationProgress: 100
  },
  {
    id: 'ind-012',
    name: 'Account Settings',
    description: 'Comprehensive account and privacy settings management',
    status: 'implemented',
    adminAccess: 'partial',
    establishmentAccess: 'none',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 98
  },
  {
    id: 'ind-013',
    name: 'Personalized Recommendations',
    description: 'AI-powered recommendations based on preferences and history',
    status: 'in_progress',
    adminAccess: 'read',
    establishmentAccess: 'none',
    individualAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 35
  },
  {
    id: 'ind-014',
    name: 'Event Calendar',
    description: 'Personal calendar for tracking joined events and bar crawls',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 85
  },
  {
    id: 'ind-015',
    name: 'Location-Based Discovery',
    description: 'Discover nearby establishments and events based on location',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'read',
    individualAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 88
  }
];
