
import { FeatureItem } from '../types';
import { comprehensivePromoterSuite } from './promoterFeatures/comprehensivePromoterSuite';
import { promotionalTools } from './promoterFeatures/promotionalTools';
import { ticketManagement } from './promoterFeatures/ticketManagement';

export const promoterFeatures: FeatureItem[] = [
  comprehensivePromoterSuite,
  promotionalTools,
  ticketManagement,
  {
    id: 'prom-001',
    name: 'Event Creation System',
    description: 'Create and manage promotional events and circuits',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 95
  },
  {
    id: 'prom-002',
    name: 'Promotion Analytics',
    description: 'Analytics dashboard for tracking promotion performance',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 90
  },
  {
    id: 'prom-004',
    name: 'Affiliate Marketing System',
    description: 'Manage affiliate programs and referral tracking',
    status: 'in_progress',
    adminAccess: 'full',
    establishmentAccess: 'partial',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'medium',
    complexity: 'high',
    implementationProgress: 55
  },
  {
    id: 'prom-005',
    name: 'Real-time Event Monitoring',
    description: 'Live monitoring of event attendance and engagement',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 88
  },
  {
    id: 'prom-006',
    name: 'Communication Hub',
    description: 'Centralized communication with attendees and venues',
    status: 'implemented',
    adminAccess: 'partial',
    establishmentAccess: 'read',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 85
  },
  {
    id: 'prom-007',
    name: 'Urgency Marketing Tools',
    description: 'Create urgency campaigns with countdown timers and limited offers',
    status: 'in_progress',
    adminAccess: 'read',
    establishmentAccess: 'none',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 40
  },
  {
    id: 'prom-009',
    name: 'Follower/Subscriber System',
    description: 'Instagram-like follow system where users can subscribe to promoters for free notifications and updates',
    status: 'in_progress',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 75
  },
  {
    id: 'prom-010',
    name: 'Dynamic Pricing Tools',
    description: 'Implement dynamic pricing based on demand and time',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'read',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 92
  },
  {
    id: 'prom-011',
    name: 'Marketing Campaign Analytics',
    description: 'Detailed analytics on marketing campaign effectiveness',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'read',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'medium',
    implementationProgress: 87
  },
  {
    id: 'prom-012',
    name: 'Dashboard Widgets',
    description: 'Customizable dashboard widgets for key metrics',
    status: 'implemented',
    adminAccess: 'read',
    establishmentAccess: 'none',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'medium',
    complexity: 'low',
    implementationProgress: 100
  },
  {
    id: 'prom-014',
    name: 'Audience Follower Tracking',
    description: 'Track and analyze follower growth and engagement',
    status: 'in_progress',
    adminAccess: 'read',
    establishmentAccess: 'none',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 65
  },
  {
    id: 'prom-015',
    name: 'Financial Management',
    description: 'Revenue tracking, expense management, and financial reporting',
    status: 'implemented',
    adminAccess: 'full',
    establishmentAccess: 'none',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'complete',
    userImpact: 'high',
    complexity: 'high',
    implementationProgress: 93
  },
  {
    id: 'prom-016',
    name: 'Cross-Platform Promotion',
    description: 'Promote events across multiple social media platforms',
    status: 'in_progress',
    adminAccess: 'read',
    establishmentAccess: 'read',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'in_progress',
    userImpact: 'medium',
    complexity: 'high',
    implementationProgress: 50
  },
  {
    id: 'prom-017',
    name: 'VIP Experience Management',
    description: 'Create and manage VIP packages and exclusive experiences',
    status: 'planned',
    adminAccess: 'read',
    establishmentAccess: 'read',
    individualAccess: 'read',
    promoterAccess: 'full',
    databaseStatus: 'not_started',
    userImpact: 'medium',
    complexity: 'medium',
    implementationProgress: 20
  },
  {
    id: 'prom-018',
    name: 'Event Collaboration Tools',
    description: 'Collaborate with other promoters and share resources',
    status: 'planned',
    adminAccess: 'partial',
    establishmentAccess: 'read',
    individualAccess: 'none',
    promoterAccess: 'full',
    databaseStatus: 'not_started',
    userImpact: 'low',
    complexity: 'medium',
    implementationProgress: 10
  }
];
